### PR TITLE
Massive overhaul of -profile, new design and and stats

### PR DESCRIPTION
**Pull request by C0rupted**
I got bored so I did this. Here are some images:
image
image
image
image

Edit: Updated images for new commit

### CODE REVIEW

**Comment by C0rupted** [comment]
Ready to merge!

**Comment by RawPikachu** [comment]
Uploaded bitmap gamemode icons to make gamemode ranking work, also fixed errors when player isn't in guild.
HUIC and HUICH stats are not line wrapping correctly, idk what would be the best way to fix that.

**Comment by C0rupted** [comment]
> Uploaded bitmap gamemode icons to make gamemode ranking work, also fixed errors when player isn't in guild. HUIC and HUICH stats are not line wrapping correctly, idk what would be the best way to fix that.

Yep, I didn't think of those cases. Thank you

**Comment by classAndrew** [comment]
Great job guys

**Pull request merged**
